# Generated by Django 2.2 on 2019-05-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('openid', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('wx_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('studentId', models.CharField(max_length=13, unique=True)),
                ('stuIdPwd', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('rate', models.FloatField(default=5.0)),
                ('receiveAddress', models.CharField(max_length=50)),
                ('received_order_count', models.IntegerField(default=10)),
                ('sended_order_count', models.IntegerField(default=10)),
                ('status', models.IntegerField(choices=[(0, 'banned'), (1, 'normal')], verbose_name='状态')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
