# Generated by Django 2.1.7 on 2019-12-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('openid', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='微信openid')),
                ('wx_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='微信名')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('studentId', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='学号')),
                ('stuIdPwd', models.CharField(blank=True, max_length=30, null=True, verbose_name='学号密码')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='学生地址')),
                ('rate', models.FloatField(default=4.0, verbose_name='评分')),
                ('receiveAddress', models.CharField(blank=True, max_length=50, null=True, verbose_name='收货地址')),
                ('received_order_count', models.IntegerField(default=100, verbose_name='收单数剩余')),
                ('sended_order_count', models.IntegerField(default=100, verbose_name='发单数剩余')),
                ('status', models.IntegerField(choices=[(0, 'banned'), (1, 'normal')], default=1, verbose_name='状态')),
                ('head_img', models.CharField(default='/static/account/img/default.jpg', max_length=2000, verbose_name='头像图片url')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '账户',
                'verbose_name_plural': '账户',
            },
        ),
    ]
