# Generated by Django 2.1.7 on 2019-12-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='receiveAddress',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='收货地址'),
        ),
    ]
