# Generated by Django 2.1.7 on 2019-12-18 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, default='', null=True, verbose_name='反馈内容')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='反馈时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user', verbose_name='反馈的用户')),
            ],
            options={
                'verbose_name': '反馈',
                'verbose_name_plural': '反馈s',
            },
        ),
    ]
