# Generated by Django 2.1.7 on 2019-12-18 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctraderecord', models.IntegerField(verbose_name='交易记录')),
                ('cpoint', models.IntegerField(default=100, verbose_name='信用积分')),
                ('cordernum', models.IntegerField(verbose_name='接单数量')),
                ('csendnum', models.IntegerField(verbose_name='发单数量')),
                ('cscore_detail', models.IntegerField(verbose_name='积分明细')),
                ('csno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_user', to='account.user', verbose_name='用户')),
            ],
        ),
    ]
