# Generated by Django 2.1.7 on 2019-12-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='announcement',
            fields=[
                ('id', models.AutoField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField(default='', max_length=20, verbose_name='标题')),
                ('content', models.TextField(default='', max_length=200, verbose_name='内容')),
                ('createdTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
            },
        ),
    ]
