# Generated by Django 2.1.7 on 2019-12-18 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order3', '0001_initial'),
        ('order2', '0001_initial'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='order2',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='order2.order2', verbose_name='发单人订单'),
        ),
        migrations.AddField(
            model_name='comment',
            name='order3',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='order3.order3', verbose_name='发单人订单'),
        ),
    ]
