# Generated by Django 2.2 on 2019-05-04 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('orderid', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('value', models.IntegerField(choices=[(0, 'low value'), (1, 'normal value'), (2, 'high value')], verbose_name='价值')),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('expireTime', models.IntegerField(choices=[(1, 'one hour'), (6, 'six hour'), (24, 'one day'), (48, 'two day'), (72, 'three day')], verbose_name='过期时长')),
                ('money', models.FloatField(default=0, verbose_name='酬劳')),
                ('pos', models.CharField(max_length=256, verbose_name='地点')),
                ('kuaidi', models.CharField(max_length=256, verbose_name='快递商')),
                ('recieved_pos', models.CharField(max_length=256, verbose_name='收货地址')),
                ('order_status', models.IntegerField(choices=[(0, 'no free lancer'), (1, 'completed'), (2, 'owner canceled'), (3, 'lancer canceled'), (4, 'has a lancer')], verbose_name='订单状态')),
                ('phone_number', models.CharField(max_length=11, verbose_name='电话号码')),
                ('code', models.CharField(max_length=64, verbose_name='取件码')),
                ('owner_name', models.CharField(max_length=256, verbose_name='主人名')),
                ('free_lancer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancer_orders', to='account.user', verbose_name='小哥')),
                ('order_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_orders', to='account.user', verbose_name='订单主人')),
            ],
        ),
    ]
